biosample: <http://ddbj.nig.ac.jp/biosample/>
biosample_ont: <http://ddbj.nig.ac.jp/ontologies/biosample/>
idorg_biosample: <http://identifiers.org/biosample/>
schema: <http://schema.org/>
prov: <http://www.w3.org/ns/prov#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
obo: <http://purl.obolibrary.org/obo/>
