title: BioProject RDF
website: https://ddbj.nig.ac.jp/
description: BioProject metadata converted to RDF
tags: [BioProject, INSDC]
provider: Bioinformation and DDBJ Center
creators:
  - name: Tazro Ohta
    affiliation: Database Center for Life Science
version: "0.1.0"
issued: 2026-04-02
licenses:
  - Attribution 4.0 International (CC BY 4.0)
